### ISSUE TITLE
[HA] Application jar file is not HA

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1039]
If application master and Gearpump Master are on a same physical machine, when the machine is down, the application may not recover properly. Although we persistent the application state across the Masters, the AppJar only contains the LocalJarStore by default, which contains the url of the application jar file. So if the Master is down, the jar file is not reachable anymore.

**Comment by whjiang** [comment]
A solution to this one is to redesign our jar storage mechanism. Currently, we store the jar file at Gearpump master. And not replicated to other masters.

We have several choices here:
1. We at masters provide some replication functionality for jar files across masters. And provide mechanisms for jar cleanup when expired. 
2. We assume there is a reliable filesystem (e.g. HDFS) and there is a dedicated folder for Gearpump. So that, we can create a dedicated sub-folder for each application and put everything (e.g. jar file) related to this application in this folder. 

Personally, I prefer solution 2 as it is much simpler. For solution 1, it will be quite complex considering HA (e.g. some master out of service sometime and return to work later...).

**Comment by clockfly** [comment]
Make this a document feature.

User can choose to use HDFS like file system to store the jar files. 
If user choose to use local directory, then he need to make sure the local directory is a NFS like directory.

@huafengw, please document this in HA guide about how to create a HA storage with NFS or somthing similar.

**Comment by clockfly** [comment]
HA Document updated on http://www.gearpump.io/site/0.6/userguide/#master-ha-guide
