### ISSUE TITLE
Dashboard failed to show metrics when applcation contains lots of tasks

### ISSUE THREAD

**Issue by huafengw** [gearpump/gearpump#1499]
Error info:
```[EndpointWriter] Transient association error (association remains live)
akka.remote.OversizedPayloadException: Discarding oversized payload sent to Actor[akka.tcp://services@127.0.0.1:52342/temp/$Cn]: max allowed size 2048000 bytes, actual size of encoded class io.gearpump.cluster.MasterToClient$HistoryMetrics was 2131922 bytes.```

How to reporduce:
Launch wordcount with 100 split and 100 sum. Wait for about 5 minutes.

**Comment by stanleyxu2005** [comment]
Hum. Increase the max package size should fix the issue. But it seems that sending the whole metrics history will sooner or later hit a max size limit.

**Comment by stanleyxu2005** [comment]
I have removed the issue from dashboard, as the main slow down is not at dashboard but backend.

**Comment by stanleyxu2005** [comment]
I launched a wordcount with 1000 split and 1000 sum. To fetch current metrics of all processors will retrieve 1.6MB data! This will happen every 2 seconds. The improvement potential will be 
1. Have a metrics service provider at backend.
2. Return aggregated metrics from the service provider.

**Comment by stanleyxu2005** [comment]
Another observation is that the cluster (one worker with 1000 slots) is not able to handle such an application, but it still attempts to launch it. I think there are at least 2 gaps:
1. During the startup, the status of the application should not be active, but submitting
2. It seems the submission is failed after a timeout. We should not allow worker have an *unreasonable* slots number according to the memory allocated to this worker, so that this application will not be accepted, because it need more slots than system can provide.
