### ISSUE TITLE
Several feature candidates

### ISSUE THREAD

**Issue by clockfly** [gearpump/gearpump#1724]
### Basic
- [ ] support changing the master address. (Master HA especially on YARN??) 
- [x] remove gearpump.hostname, or use default value if not specified. (deployment problem. Decision: remove gearpump.hostname).
- [ ] support futures in tasks, so that we can do IO call asynclly. The difficulty is to track the timestamp. (If requiring order keeping, then the future should keep the message order). Wether we should allow future to own its own thread pool?
- [x] add more connector module to external database,twitter, weibo, message queue, parquet, and etc.. (We can reference storm for examples..., maybe some adapter for storm and other engines????) 
- [ ] Migrate the akka-stream experiment module to akka-stream 2.0. 
- [ ] Allow user to switch options between "at most once", "exactly-once", and "at least once" (allow user to switch...)
- [x] Support disabling POST/DELETE/PUT so that we can demo this on public website. (add a config to disable POST/DELETE/PUT, and the UI should show errors friendly)
(AR: check the cache policy of javascript so that the UI will refresh)

### resource scheduling
- [x] yarn module, allow user to dynamically add/remove a gearpump worker.
- [ ] yarn module, need to handle resource manager failure or resource preemption
- [ ] support mesos (typesafe?) 
- [ ] support fine-grained resoure scheduling. (incrementally ask yarn for new resource)
- [x] Support resource containing/isolation for different application. (useful especially for big enterprise. How???, Whether we can leverage yarn to do resource contianing? Whether we can leverage CDH parcel to do resource containing?)(#1723)

### Storm
- [x] storm module, verifed storm support, verified support for trident. Storm use exclusive thread, while Gearpump use shared thread pool. Storm user may do blocking IO in storm applications.
- [x] Support StreamCQL (storm module able to handle this???)

### HA
- [ ] Enable reliable proxy pattern, so that we can protect against unexpected network glitch. 

### Security
- [x] Enable authentication/authorization, including UI. (akka-http has limited support for authentication...)
- [x] Support Kerberos enabled service like HDFS/HBase.... ()

### Other
- [ ] window function support in high level DSL.  (timestamp?)
- [ ] support DAG with loops.
- [ ] IoT show case(test deployment model)
- [ ] SAMOA and other machine learning capacities. 
- [x] GC optimization. ??

UI feature request can be found at: https://github.com/gearpump/gearpump/issues/1678

**Comment by manuzhang** [comment]
how about #1723 ?

**Comment by manuzhang** [comment]
features | Apache Jira 
---------- | ---------------- 
support changing the master address  | https://issues.apache.org/jira/browse/GEARPUMP-87
support futures in tasks, so that we can do IO call asynclly | https://issues.apache.org/jira/browse/GEARPUMP-81
Migrate the akka-stream experiment module to akka-stream 2.0 | https://issues.apache.org/jira/browse/GEARPUMP-22
Allow user to switch options between "at most once", "exactly-once", and "at least once" | https://issues.apache.org/jira/browse/GEARPUMP-33
yarn module, need to handle resource manager failure or resource preemption | https://issues.apache.org/jira/browse/GEARPUMP-43
support mesos | https://issues.apache.org/jira/browse/GEARPUMP-88
support fine-grained resoure scheduling | https://issues.apache.org/jira/browse/GEARPUMP-89

**Comment by manuzhang** [comment]
All feature candidates have been move to Apache jira as in the above table. Close this.
