### ISSUE TITLE
0.8.0 Release does not include scala 2.10 build

### ISSUE THREAD

**Issue by vishalkuo** [gearpump/gearpump#2033]
https://github.com/gearpump/gearpump/releases/tag/0.8.0 does not contain a release for scala 2.10, as a result, following the download link from http://www.gearpump.io/download.html results in a 404. Not sure if this is the right place to be raising this, I just figured it ought to be documented somewhere.

**Comment by clockfly** [comment]
@vishalkuo 

Thanks for reporting this:

The 0.8 doesn't contains build for scala2.10. The reason is that Gearpump 0.8 use Akka 2.4.2, while the Akka 2.4.2 no longer support for scala 2.10. See http://akka.io/news/2015/09/30/akka-2.4.0-released.html

The doc site need to be updated. Do you need to use Scala 2.10? Or can Scala2.11 is also OK?

**Comment by vishalkuo** [comment]
Not required, just thought I'd raise it somewhere to make it known! Thanks!

**Comment by clockfly** [comment]
@vishalkuo 

Thanks for reporting this!
I have created an issue at Jira https://issues.apache.org/jira/browse/GEARPUMP-26

We are trying to migrate all issues to Apache Jira :)

**Comment by clockfly** [comment]
Tracked by https://issues.apache.org/jira/browse/GEARPUMP-26

Will close this one:)
