### ISSUE TITLE
TaskActor start and next messages

### ISSUE THREAD

**Issue by sirinath** [gearpump/gearpump#288]
I have been thinking about this. I think the following issues may arise if you have to send messages to self to start and process next:

 - Ideally should not be needed as it is boilerplate
 - Can cause many bugs as you might forget
 - Cannot reuse TaskActor at other stages of a pipeline bases on if this message is needed or not
 - Takes some cycles handle these messages

Perhaps it will be best to avoid this.

**Comment by clockfly** [comment]
The original thought is to treat source processor, intermediate processor, and sink processor the same way, so that every module is driven by message explicitly. 

Sometimes, source task(no in-degree in the graph) may also listen to data from external services, in that case,the source task don't need to send self explict internal message like "Start" and "Next", they are driven by external messages


.


We will find out

**Comment by sirinath** [comment]
Ideally the user should not worry about these messages. Having the user do this can easily bead to issues in large complex systems and interaction where all is not developed by one use. This is like manual memory management. If you do it right all is good. If mess up the bugs are very hard to track and fix.

**Comment by clockfly** [comment]
Thanks, 

we are working on refactoring the streaming api. We will weight whether we can add an intermediate adapter in between to hide the internal self messages.

**Comment by sirinath** [comment]
Also some thing to consider is the number of productive lines for code when writing a simple workflow. Of course for large problems this will not matter. For something like the example given you need a lot of boilerplate to be written.

**Comment by sirinath** [comment]
Any headway in this?

**Comment by clockfly** [comment]
@sirinath ,

Thank you for your interest. We have been working on refactoring streaming appmaster, to better handle the fail-over scenario. Next task I think is to refactor the TaskActor.

Besides the reason you mentioned, there are several other requirements to consider in total when doing the refactory:
1. When there is message loss, and trigger mesage replay, existing state in memory should not be lost.
2. The source actors should also accept push-style messages. For example, A device may push the message directly into the source task actors. 
3. For exactly once mesage delivery, the state in memory need to be checkpointed, the state storage api should be part of the TaskActor.
4. How to track the clock timestamp of task effectively if this task has no output mesage.

In point 2, message will be pushed to the source actors, so the source actors still need to be respond to external messages. 

The main difficulty for this issue is that, if we remove the onStart and onNext in source actors, how can the source actors still be able to receive and respond to external message input, like IOT events, user command input?

By the way, how is your use case looks like? If you prefer, we can arrange a phone call to discuss it so that we can support you in priority.

**Comment by sirinath** [comment]
I will take this GearPump User List. This is better than phone call.

**Comment by clockfly** [comment]
This is related with #351

**Comment by okapies** [comment]
Hi, I recently found this project. The "stream processor in Akka" concept really impressed me!

I favor a proposal from @sirinath. I would like to add that, in the terms of Akka application, we should implement business logics in *"Plain Old Actor"* instead of `TaskActor`, handle initialization/finalize logic in `preStart()` and `postStop()` method, and notify the actor of both data events and lifecycle events through actor messages instead of callbacks (at least in the bottom layer of the API).

If we do that, for example, I imagine we can write the `Sum` processor in [the document](http://www.gearpump.io/site/documents/how_to_write_a_streaming_application/) as follows:

```scala
class SumActor(taskContext : TaskContext, userConf : UserConfig, startTime: StartTime) extends Actor {
  ...
  override def preStart(): Unit = {
    import context.dispatcher
    scheduler = context.system.scheduler.schedule(
      new FiniteDuration(5, TimeUnit.SECONDS), new FiniteDuration(5, TimeUnit.SECONDS), self, "tick")
  }

  override def receive: Receive = {
    case m: Message =>
      val current = map.getOrElse(m.msg.asInstanceOf[String], 0L)
      wordCount += 1
      map.put(m.msg.asInstanceOf[String], current + 1)
    case "tick" => reportWordCount()
  }

  override def postStop: Unit = {
    scheduler.cancel()
  }
  ...
}
```

`TaskActor` (we should call it `TaskExecutor` in this sense) instantiates the processor such like `system.actorOf(Props(classOf[SumActor], ctx, conf, startTime))`, keep transferring events and supervise it (I'm wondering whether the idea of passing the contexts through constructor is acceptable).

One of the good things of this method is that we simply restart the actor when our actor get mad and can keep states held in the `TaskActor`.

**Comment by kkasravi** [comment]
Thanks @okapies for the feedback. I agree methods like preStart, receive and postStop have value within this framework. Also a good point regarding using events vs. callbacks. I know Tez and some other DAG based frameworks utilize events within the DAG especially for operations like broadcast. Frameworks we're also reviewing are akka-streams and flink - especially their ability to distribute closures from a high level API. We are actively working on the TaskActor / DAG API - and will surface a design in the near future. We'll update this issue as we make progress. Thanks!

**Comment by okapies** [comment]
Thanks for your reply. That sound great! I'm looking foward to it.

**Comment by clockfly** [comment]
@okapies 

Thanks for your interest.

Currently we are adopting somewhat a strict interface for Task, so that it is more easy to evolve this in future. As you may know, besides handling message, the TaskActor also need to do a couple of other things, like flow control, message loss detection, message replay, state checkpointting and recovery. To do these things, some special messages are defined and they need to be handled specifically. So, a wrapper for task is needed so that the underlying details is transparent to user.

**Comment by okapies** [comment]
@clockfly Yes, what I said in the previous post is just a topic pertaining to "composition over inheritance". Tasks implemented in a subclass of any framework-provided class will be inherently bound to the implicit and explicit context of that superclass, as @sirinath exactly pointed out. I think "message-passing" is a reasonable way to achieve delegation in the actor model.

The downside of messaging (in Akka) is that we can't have type signature to statically indicate what kind of events are come from the framework ([Akka Typed](http://doc.akka.io/docs/akka/snapshot/scala/typed.html) will save us in the near future but is immature).

But this turns into another advantage. Actors are able to receive, as the above example shown, any type of message other than data events routed by the runtime such like user-defined clock signal, asynchronous response from https://pic.twitter.com to fetch images contained in the tweet, and result of batch processing.

I think Tumblr's [Colossus](http://tumblr.github.io/) is a good example of leveraging actors in event-processing system. Colossus has [actor-based event loop](http://tumblr.github.io/colossus/docs/core/) to process incoming events while utilizing message-passing to easily communicate with other actors. Colossus also provides [object-oriented and functional interface](http://tumblr.github.io/colossus/docs/quickstart/) on top of it.

And in my opinion, transparency isn't always good in some situation. Storm, for example, provides good transparency of underlying behavior and network location, but at the same time what is happen in runtime is invisible to users and hard to handle. When something goes wrong, the users will face the difficulties of inspecting runtime behavior of Storm engine to debug our spouts and bolts and coordinate some runtime parameters.

**Comment by manuzhang** [comment]
closing this. we can continue discussion on 

* dev@gearpump.incubator.apache.org
* user@gearpump.incubator.apache.org
