### ISSUE TITLE
Compare Heron with GearPump

### ISSUE THREAD

**Issue by kkasravi** [gearpump/gearpump#986]
[Story](https://www.pivotaltracker.com/story/show/96047698)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/985)
Compare the recent twitter framework Heron with GearPump

**Comment by kkasravi** [comment]
Add deck to either gearpump.io or under docs.

**Comment by manuzhang** [comment]
I'd like to post an draft here for comments and discussions.

## Overview

**Heron's data model and API** are identical to Storm. Heron also inherits Storm's At-most-once / At-least-once (by acknowledgement) tuple processing semantics.

**Heron's architecture** is similar to that of MapReduce-on-YARN, where a topology is submitted to an [Aurora](https://github.com/apache/aurora) scheduler and run as an Aurora job consisting of several containers (Linux cgroups). Unlike Storm, topologies are isolated and each topology is managed independently by a **Topology Master (TM)** (like ApplicationMaster). Each container has a **Stream Manager (SM)** which sends and receives tuples to its local **Heron Instance (HI) **s. A Heron Instance is one JVM running a single Task (Spout/Bolt)

## Comparison with Gearpump

I will talk more about where Gearpump lacks here, which could direct for future improvement. 

### resources allocation
Heron schedules and allocates resource through a sophisticated scheduler. Resources are isolated by containers. It allows a topology writer to specify exactly the resource for each component. Gearpump's scheduler is quite simple and a worker's available resources are not even mapped to hardware resources. Tasks' resources are not isolated. 

### Backpressure
Heron implemented a backpressure approach called **Spout Backpressure**. When an SM realizes one or more of its HIs are slowsing down , it sends a **start backpressure** message to other SMs requesting them to clamp down their local spouts. Once the slow HI catches up, the local SM sends **stop backpressure** messages to other SMs. Gearpump employs a what Heron called **Stage-by-Stage Backpressure** where backpressure is propagated from the slow task back to a source task stage-by-stage.

### debug-ability
Since each Heron Instance (JVM) is executing only a single task, it is easy to debug that instance. A Gearpump executor (JVM) usually runs multiple task which makes debugging not easy. Further,  since logs from multiple tasks are written to single a file it's hard to identify errors or exceptions associated with a single task from the log.
